### PR TITLE
RN63 updates

### PR DESCRIPTION
**Pull request by raimonkh**
Actual change, Importing PickerIOS from a dfiferent place

### CODE REVIEW

**Review by maxkomarychev — CHANGES_REQUESTED** [review]
1. please revert changes to quotes to retain original style
2. pleas remove autogenerated yarn files

**Review by yonatan-altaraz — APPROVED** [review]

**Comment by raimonkh** [comment]
@maxkomarychev done

**Review by maxkomarychev — APPROVED** [review]

**Comment by raimonkh** [comment]
@maxkomarychev funny story seems this is deprecated since 61, not sure why it didn't fail

**Comment by maxkomarychev** [comment]
maybe it was backward compatible and printed a warning? 🤔

**Comment by maxkomarychev** [comment]
https://github.com/facebook/react-native/commit/6d54423b788ba2f0ec5c7eda9b2ab3d66a5bd529

**Pull request merged**
